# Generated by Django 4.1.5 on 2023-01-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookit_app', '0003_alter_recipe_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(max_length=255),
        ),
    ]
